# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

mod_version=1.3.0
maven_group=committee.nova.mods
enabled_platforms=fabric,forge

# Mod properties
mod_id=moreleads
mod_name=MoreLeads
mod_author=cnlimiter
license=A GPL-3.0 license
credits=
description=More Leads for Minecraft.
mod_version_label=release


# Minecraft properties
minecraft_version = 1.16.5

# Dependencies
minecraft_version_range=1.16.*

fabric_loader_version = 0.16.14
fabric_api_version = 0.42.0+1.16

forge_version = 1.16.5-36.2.42
forge_loader_version_range=[34,)
forge_version_range=[34,)
